build: build-proto
	@echo "building..."
	@go build -o ./bin/miner ./cmd/miner

deps:
	@echo "refer https://grpc.io/docs/languages/go/quickstart/#prerequisites for gRPC and Protobuf dependencies"
	@echo "collecting dependencies..."
	@go mod download
	@echo "done"

test:
	@go test -v ./pkg/hash ./internal/service

bench:
	@go test ./pkg/hash -run=Bench -bench=.

cover:
	@go test ./pkg/hash ./internal/service -coverprofile=cover.txt && \
	go tool cover -html=cover.txt -o cover.html && rm cover.txt

build-proto:
	@protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    ./pkg/autogenerated/miner.proto

run-server: build
	@./bin/miner server

run-client: build
	@./bin/miner client