package hash

import (
	pb "github.com/DanialDMQ/Goob/pkg/autogenerated"
)

type Hash interface {
	GetRecord(reqStruct *pb.MinerRequest, nonce int64) (string, error)
	GetSha256(str string) (string, error)
}
